export const getKeys = (constant) => Reflect.ownKeys(constant).map(constantKey => constant[constantKey].key);

export const USER_ROLES = {
  // USER: { key: 'USER', label: 'User' },
  SUPER_ADMIN: { key: 'SUPER_ADMIN', label: 'Super Admin' },
  ADMIN: { key: 'ADMIN', label: 'Admin' },
  STATE_LEVEL_USER: { key: 'STATE_LEVEL_USER', label: 'State Level User' },
  BLOCK_LEVEL_USER: { key: 'BLOCK_LEVEL_USER', label: 'Block level user' },
  DISTRICT_LEVEL_USER: { key: 'DISTRICT_LEVEL_USER', label: 'District level user' }
};

export const QUESTION_CATEGORY = {
  CYCLE_SCHEM: { key: 'CYCLE_SCHEM', label: 'Cycle Schema' },
  MAHILA_JEEVIKA: { key: 'MAHILA_JEEVIKA', label: 'Mahila Jeevika' },
  HEALTH_DEPARTMENT: { key: 'HEALTH_DEPARTMENT', label: 'Health Department' },
  EDUCATION_DEPARTMENT: { key: 'EDUCATION_DEPARTMENT', label: 'Education Department' },
  STUDENT: { key: 'STUDENT', label: 'Student' },
};

export const DISTRICT = [
  "Araria",
  "Arwal",
  "Aurangabad",
  "Banka",
  "Begusarai",
  "Bhabhua",
  "Bhagalpur",
  "Bhojpur",
  "Buxar",
  "Darbhanga",
  "East Champaran",
  "Gaya",
  "Gopalganj",
  "Jamui",
  "Jehanabad",
  "Katihar",
  "Khagaria",
  "Kishanganj"
];


export const VIDHANSABHA = [
  "Valmiki Nagar (Vidhan Sabha constituency)",
  "Ramnagar, Paschim Champaran (Vidhan Sabha constituency)",
  "Narkatiaganj (Vidhan Sabha constituency)",
  "Bagaha (Vidhan Sabha constituency)",
  "Lauriya (Vidhan Sabha constituency)",
  "Nautan (Vidhan Sabha constituency)",
  "Chanpatia (Vidhan Sabha constituency)",
  "Bettiah (Vidhan Sabha constituency)",
  "Sikta (Vidhan Sabha constituency)",
  "Raxaul (Vidhan Sabha constituency)",
  "Sugauli (Vidhan Sabha constituency)",
  "Narkatiya (Vidhan Sabha constituency)",
  "Harsidhi (Vidhan Sabha constituency)",
  "Govindganj (Vidhan Sabha constituency)",
  "Kesaria (Vidhan Sabha constituency)",
  "Kalyanpur, Purvi Champaran (Vidhan Sabha constituency)",
  "Pipra, Purvi Champaran (Vidhan Sabha constituency)",
  "Madhuban (Vidhan Sabha constituency)",
  "Motihari (Vidhan Sabha constituency)",
  "Chiraia (Vidhan Sabha constituency)",
  "Dhaka (Vidhan Sabha constituency)",
  "Sheohar (Vidhan Sabha constituency)",
  "Riga (Vidhan Sabha constituency)",
  "Bathnaha (Vidhan Sabha constituency)",
  "Parihar (Vidhan Sabha constituency)",
  "Sursand (Vidhan Sabha constituency)",
  "Bajpatti (Vidhan Sabha constituency)",
  "Sitamarhi (Vidhan Sabha constituency)",
  "Runnisaidpur (Vidhan Sabha constituency)",
  "Belsand (Vidhan Sabha constituency)",
  "Harlakhi (Vidhan Sabha constituency)",
  "Benipatti (Vidhan Sabha constituency)",
  "Khajauli (Vidhan Sabha constituency)",
  "Babubarhi (Vidhan Sabha constituency)",
  "Bisfi (Vidhan Sabha constituency)",
  "Madhubani (Vidhan Sabha constituency)",
  "Rajnagar, Madhubani (Vidhan Sabha constituency)",
  "Jhanjharpur (Vidhan Sabha constituency)",
  "Phulparas (Vidhan Sabha constituency)",
  "Laukaha (Vidhan Sabha constituency)",
  "Nirmali (Vidhan Sabha constituency)",
  "Pipra, Supaul (Vidhan Sabha constituency)",
  "Supaul (Vidhan Sabha constituency)",
  "Triveniganj (Vidhan Sabha constituency)",
  "Chhatapur (Vidhan Sabha constituency)",
  "Narpatganj (Vidhan Sabha constituency)",
  "Raniganj, Araria (Vidhan Sabha constituency)",
  "Forbesganj (Vidhan Sabha constituency)",
  "Araria (Vidhan Sabha constituency)",
  "Jokihat (Vidhan Sabha constituency)",
  "Sikti (Vidhan Sabha constituency)",
  "Bahadurganj (Vidhan Sabha constituency)",
  "Thakurganj (Vidhan Sabha constituency)",
  "Kishanganj (Vidhan Sabha constituency)",
  "Kochadhaman (Vidhan Sabha constituency)",
  "Amour (Vidhan Sabha constituency)",
  "Baisi (Vidhan Sabha constituency)",
  "Kasba, Purnia (Vidhan Sabha constituency)",
  "Banmankhi (Vidhan Sabha constituency)",
  "Rupauli (Vidhan Sabha constituency)",
  "Dhamdaha (Vidhan Sabha constituency)",
  "Purnia (Vidhan Sabha constituency)",
  "Katihar (Vidhan Sabha constituency)",
  "Kadwa (Vidhan Sabha constituency)",
  "Balrampur, Katihar (Vidhan Sabha constituency)",
  "Pranpur (Vidhan Sabha constituency)",
  "Manihari (Vidhan Sabha constituency)",
  "Barari (Vidhan Sabha constituency)",
  "Korha (Vidhan Sabha constituency)",
  "Alamnagar (Vidhan Sabha constituency)",
  "Bihariganj (Vidhan Sabha constituency)",
  "Singheshwar (Vidhan Sabha constituency)",
  "Madhepura (Vidhan Sabha constituency)",
  "Sonbarsha, Saharsa (Vidhan Sabha constituency)",
  "Saharsa (Vidhan Sabha constituency)",
  "Simri Bakhtiarpur (Vidhan Sabha constituency)",
  "Mahishi (Vidhan Sabha constituency)",
  "Kusheshwar Asthan (Vidhan Sabha constituency)",
  "Gaura Bauram (Vidhan Sabha constituency)",
  "Benipur (Vidhan Sabha constituency)",
  "Alinagar (Vidhan Sabha constituency)",
  "Darbhanga Rural (Vidhan Sabha constituency)",
  "Darbhanga (Vidhan Sabha constituency)",
  "Hayaghat (Vidhan Sabha constituency)",
  "Bahadurpur (Vidhan Sabha constituency)",
  "Keoti (Vidhan Sabha constituency)",
  "Jale (Vidhan Sabha constituency)",
  "Gaighat (Vidhan Sabha constituency)",
  "Aurai (Vidhan Sabha constituency)",
  "Minapur (Vidhan Sabha constituency)",
  "Bochahan (Vidhan Sabha constituency)",
  "Sakra (Vidhan Sabha constituency)",
  "Kurhani (Vidhan Sabha constituency)",
  "Muzaffarpur (Vidhan Sabha constituency)",
  "Kanti (Vidhan Sabha constituency)",
  "Baruraj (Vidhan Sabha constituency)",
  "Paroo (Vidhan Sabha constituency)",
  "Sahebganj, Muzaffarpur (Vidhan Sabha constituency)",
  "Baikunthpur (Vidhan Sabha constituency)",
  "Barauli, Bihar (Vidhan Sabha constituency)",
  "Gopalganj (Vidhan Sabha constituency)",
  "Kuchaikote (Vidhan Sabha constituency)",
  "Bhore (Vidhan Sabha constituency)",
  "Hathua (Vidhan Sabha constituency)",
  "Siwan (Vidhan Sabha constituency)",
  "Ziradei (Vidhan Sabha constituency)",
  "Darauli (Vidhan Sabha constituency)",
  "Raghunathpur, Siwan (Vidhan Sabha constituency)",
  "Daraunda (Vidhan Sabha constituency)",
  "Barharia (Vidhan Sabha constituency)",
  "Goriakothi (Vidhan Sabha constituency)",
  "Maharajganj, Siwan (Vidhan Sabha constituency)",
  "Ekma (Vidhan Sabha constituency)",
  "Manjhi (Vidhan Sabha constituency)",
  "Baniapur (Vidhan Sabha constituency)",
  "Taraiya (Vidhan Sabha constituency)",
  "Marhaura (Vidhan Sabha constituency)",
  "Chapra, Saran (Vidhan Sabha constituency)",
  "Garkha (Vidhan Sabha constituency)",
  "Amnour (Vidhan Sabha constituency)",
  "Parsa (Vidhan Sabha constituency)",
  "Sonepur (Vidhan Sabha constituency)",
  "Hajipur (Vidhan Sabha constituency)",
  "Lalganj (Vidhan Sabha constituency)",
  "Vaishali (Vidhan Sabha constituency)",
  "Mahua (Vidhan Sabha constituency)",
  "Raja Pakar (Vidhan Sabha constituency)",
  "Raghopur, Vaishali (Vidhan Sabha constituency)",
  "Mahnar (Vidhan Sabha constituency)",
  "Patepur (Vidhan Sabha constituency)",
  "Kalyanpur, Samastipur (Vidhan Sabha constituency)",
  "Warisnagar (Vidhan Sabha constituency)",
  "Samastipur (Vidhan Sabha constituency)",
  "Ujiarpur (Vidhan Sabha constituency)",
  "Morwa (Vidhan Sabha constituency)",
  "Sarairanjan (Vidhan Sabha constituency)",
  "Mohiuddinnagar (Vidhan Sabha constituency)",
  "Bibhutipur (Vidhan Sabha constituency)",
  "Rosera (Vidhan Sabha constituency)",
  "Hasanpur (Vidhan Sabha constituency)",
  "Cheria-Bariarpur (Vidhan Sabha constituency)",
  "Bachhwara (Vidhan Sabha constituency)",
  "Teghra (Vidhan Sabha constituency)",
  "Matihani (Vidhan Sabha constituency)",
  "Sahebpur Kamal (Vidhan Sabha constituency)",
  "Begusarai (Vidhan Sabha constituency)",
  "Bakhri (Vidhan Sabha constituency)",
  "Alauli (Vidhan Sabha constituency)",
  "Khagaria (Vidhan Sabha constituency)",
  "Beldaur (Vidhan Sabha constituency)",
  "Parbatta (Vidhan Sabha constituency)",
  "Bihpur (Vidhan Sabha constituency)",
  "Gopalpur (Vidhan Sabha constituency)",
  "Pirpainti (Vidhan Sabha constituency)",
  "Kahalgaon (Vidhan Sabha constituency)",
  "Bhagalpur (Vidhan Sabha constituency)",
  "Sultanganj (Vidhan Sabha constituency)",
  "Nathnagar (Vidhan Sabha constituency)",
  "Amarpur (Vidhan Sabha constituency)",
  "Dhoraiya (Vidhan Sabha constituency)",
  "Banka (Vidhan Sabha constituency)",
  "Katoria (Vidhan Sabha constituency)",
  "Belhar (Vidhan Sabha constituency)",
  "Tarapur (Vidhan Sabha constituency)",
  "Munger (Vidhan Sabha constituency)",
  "Jamalpur, Munger (Vidhan Sabha constituency)",
  "Suryagarha (Vidhan Sabha constituency)",
  "Lakhisarai (Vidhan Sabha constituency)",
  "Sheikhpura (Vidhan Sabha constituency)",
  "Barbigha (Vidhan Sabha constituency)",
  "Asthawan (Vidhan Sabha constituency)",
  "Biharsharif (Vidhan Sabha constituency)",
  "Rajgir (Vidhan Sabha constituency)",
  "Islampur, Nalanda (Vidhan Sabha constituency)",
  "Hilsa (Vidhan Sabha constituency)",
  "Nalanda (Vidhan Sabha constituency)",
  "Harnaut (Vidhan Sabha constituency)",
  "Mokama (Vidhan Sabha constituency)",
  "Barh (Vidhan Sabha constituency)",
  "Bakhtiarpur (Vidhan Sabha constituency)",
  "Digha (Vidhan Sabha constituency)",
  "Bankipur (Vidhan Sabha constituency)",
  "Kumhrar (Vidhan Sabha constituency)",
  "Patna Sahib (Vidhan Sabha constituency)",
  "Fatuha (Vidhan Sabha constituency)",
  "Danapur (Vidhan Sabha constituency)",
  "Maner (Vidhan Sabha constituency)",
  "Phulwari (Vidhan Sabha constituency)",
  "Masaurhi (Vidhan Sabha constituency)",
  "Paliganj (Vidhan Sabha constituency)",
  "Bikram (Vidhan Sabha constituency)",
  "Sandesh (Vidhan Sabha constituency)",
  "Barhara (Vidhan Sabha constituency)",
  "Arrah (Vidhan Sabha constituency)",
  "Agiaon (Vidhan Sabha constituency)",
  "Tarari (Vidhan Sabha constituency)",
  "Jagdishpur (Vidhan Sabha constituency)",
  "Shahpur (Vidhan Sabha constituency)",
  "Brahampur (Vidhan Sabha constituency)",
  "Buxar (Vidhan Sabha constituency)",
  "Dumraon (Vidhan Sabha constituency)",
  "Rajpur (Vidhan Sabha constituency)",
  "Ramgarh, Kaimur (Vidhan Sabha constituency)",
  "Mohania (Vidhan Sabha constituency)",
  "Bhabua (Vidhan Sabha constituency)",
  "Chainpur (Vidhan Sabha constituency)",
  "Chenari (Vidhan Sabha constituency)",
  "Sasaram (Vidhan Sabha constituency)",
  "Kargahar (Vidhan Sabha constituency)",
  "Dinara (Vidhan Sabha constituency)",
  "Nokha (Vidhan Sabha constituency)",
  "Dehri (Vidhan Sabha constituency)",
  "Karakat (Vidhan Sabha constituency)",
  "Arwal (Vidhan Sabha constituency)",
  "Kurtha (Vidhan Sabha constituency)",
  "Jehanabad (Vidhan Sabha constituency)",
  "Ghosi (Vidhan Sabha constituency)",
  "Makhdumpur (Vidhan Sabha constituency)",
  "Goh (Vidhan Sabha constituency)",
  "Obra (Vidhan Sabha constituency)",
  "Nabinagar (Vidhan Sabha constituency)",
  "Kutumba (Vidhan Sabha constituency)",
  "Aurangabad (Bihar Vidhan Sabha constituency)",
  "Rafiganj (Vidhan Sabha constituency)",
  "Gurua (Vidhan Sabha constituency)",
  "Sherghati (Vidhan Sabha constituency)",
  "Imamganj (Vidhan Sabha constituency)",
  "Barachatti (Vidhan Sabha constituency)",
  "Bodh Gaya (Vidhan Sabha constituency)",
  "Gaya Town (Vidhan Sabha constituency)",
  "Tikari (Vidhan Sabha constituency)",
  "Belaganj (Vidhan Sabha constituency)",
  "Atri (Vidhan Sabha constituency)",
  "Wazirganj (Vidhan Sabha constituency)",
  "Rajauli (Vidhan Sabha constituency)",
  "Hisua (Vidhan Sabha constituency)",
  "Nawada (Vidhan Sabha constituency)",
  "Gobindpur (Vidhan Sabha constituency)",
  "Warsaliganj (Vidhan Sabha constituency)",
  "Sikandra (Bihar Vidhan Sabha constituency)",
  "Jamui (Vidhan Sabha constituency)",
  "Jhajha (Vidhan Sabha constituency)",
  "Chakai (Vidhan Sabha constituency)"
]